This will have [[https://www.scannedinavian.com/about.html][my]] notes for chapter 1 of [[https://press.stripe.com/the-art-of-doing-science-and-engineering][The Hamming book]].

"You will get out of this course only as much as you put in"

"Education is what, when, and why to do things. Training is how to do it."

"You need to know both what to do, and how to do it."

"Knowledge has doubled every 17 years."

Hypothesis: The US political climate will likely produce a dip in knowledge production.
How to measure this? count of publications over time? education participation over time?
Is a record of "breakthroughs" so I could try measuring that over time?

Aha, back of the envelope calculations appear! Are these the same as Fermi estimations?
- [ ] train Fermi estimations
- [ ] does detail of the estimation matter?
  "Having done the calculation, you are much more likely to retain the results in your mind."
  I suspect that's true for reading about new algorithms or libraries.
  So, I will learn new patterns better if I immediately use them for something, that makes sense!
- [ ] Personal todo: try to hack new bloom filter stuff https://dl.acm.org/doi/10.1145/3651890.3672219 into [[https://github.com/shapr/bloohm][bloohm]] ?


#+begin_src fundamental
  Concentrate on fundamentals, at least what /you think/ at the time are
  fundamentals, and also develop the ability to learn new fields of
  knowledge when they arise so you will not be left behind, as so many
  good engineers are in the long run.
#+end_src

I first read [[http://lambda-the-ultimate.org/node/668][this book]] somewhere between 2005 and 2007, and focussing on the fundamentals has paid off.
But as mentioned in the "apply what you learn" snippet earlier, you gotta have a balance between learning and doing.
What's a new field to learn? FPGA dev? 🤔

#+begin_src fundamental
  I am a veteran of learning enough to get along without at the same
  time devoting all my effort to learning new topics and thereby not
  contributing my share to the total effort of the organization.
#+end_src

#+begin_src fundamental
  In science if you know what you are doing you should not be doing it.

  In engineering if you do not know what you are doing you should not be doing it.
#+end_src

Become an autodidact! Teach yourself everything you can!

Human limitations have more effect than technological limitations. (support: Drone use in Ukraine?)

1. history is seldom reported at all accurately, and I have found no
   two reports of what happened at Los Alamos during WW-II seem to
   agree.
2. due to the pace of progress the future is rather disconnected from
   the past; the presence of the modern computer is an example of the
   great differences which have arisen.

"Unforeseen technological inventions can completely upset the most careful predictions."

#+begin_src fundamental
  The drunken sailor who staggers to the left or right with n independent random steps will, on average, end up about √n steps from the origin.
  If there is a pretty girl in one direction, his steps will go a distance proportional to n.
#+end_src

"No vision, not much of a future."

Build your own vision! Don't be afraid to change direction when you learn new stuff!

"I devoted 10% of my time to trying to understand what would happen in the future of computing"

- What is possible? (science)
- What is likely to happen? (engineering)
- What is desirable to happen? (ethics)

"having a vision is what separates leaders from followers"

#+begin_src fundamental
  I am preaching the message that, with apparently only one life to live
  on this earth, you ought to try to make significant contribution to
  humanity rather than just get along through life comfortably - that
  the life of trying to achieve excellence in some area is in itself a
  worthy goal for your life.

  It has often been observed the true gain is in the struggle and not in
  the achievement - a life without struggle on your part to make
  yourself excellent is hardly a life worth living.
#+end_src
HECK YEAH! You go Hamming!

"The unexamined life is not worth living" -- Socrates
